server:
  port: 18080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hfq-shimanqiang/hello-hello.git
          basedir: target/config
health:
  config:
    enabled: true
    time-to-live: 0

